// Generated by Wrangler on Wed Jun 19 2024 09:02:40 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: "pk_test_YWxpdmUtY2hpcG11bmstOTcuY2xlcmsuYWNjb3VudHMuZGV2JA";
}
